deploy: True
tag: scratch
seed: 42

device : "mps"
bf16: True
epochs: 1

data:
  language: 'expr' # ['english', 'expr', 'dyck']
  config:
    n_digits: 10
    n_ops: 3
    error_type: 'sub' # ['swp', 'ins', 'del', 'sub']
    error_rate: 0.1
  alpha: 1e5 # depends on the prior type
  prior_type: 'dirichlet' # ['dirichlet', 'zipfian', 'structured_zeros', 'uniform']
  max_sample_length: 128
  num_iters: 1e6
  batch_size: 128 
  # CORR: > 0 causes an error in pickling that I didn't understand.
  num_workers: 0

model:
  compile: False
  context_size: 256
  n_layer: 2
  n_head: 2
  n_embd: 128
  dropout: 0.0
  bias: False
  mlp: True
  use_pretrained: False
  pretrain_dir: './pretrained/latest_ckpt.pt'

optimizer:
  learning_rate: 1e-3
  weight_decay: 1e-4
  beta1: 0.9
  beta2: 0.95
  grad_clip: 1.0

  decay_lr: True
  warmup_iters: 200
  min_lr: 9e-4
  total_iters: 1000

eval:
  save_tables: False
  grammar: True

log: 
  save_multiple: False
  log_interval: 10
  eval_interval: 100
  save_interval: 100
  free: False


# Nested configs. Disable hydra logging
defaults:
  - _self_
  - override hydra/job_logging: disabled
  - override hydra/hydra_logging: disabled

# Disable hydra directory structure
hydra:
  output_subdir: Null
  job:
    chdir: False
  run:
    dir: .

  sweep:
    dir: .
    subdir: .
